### ISSUE TITLE
Play/download with custom search query does not work with dev version of elementum

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/context.quasar#29]
Search starts but then elementum does not show window with results.

пробовал на 
https://trakt.tv/shows/konosuba-god-s-blessing-on-this-wonderful-world/seasons/0/episodes/2
https://trakt.tv/shows/konosuba-god-s-blessing-on-this-wonderful-world/seasons/3/episodes/1

в логе видно что торренты нашлись, но окно с результатами не появилось и ошибок в логе тоже нет.

лог https://paste.ubuntu.com/p/97BXGZ6Ydr/

**Comment by elgatito** [comment]
@antonsoroko 

```
2024-04-12 15:41:27.123 T:13839 warning <general>: [script.elementum.burst] Providers returned 2 results in 3.45 seconds
```

Надо смотреть какие там результаты вернулись. Если результаты потом сам Elementum не может скачать и в результате получается пустой список - то и окна не выводится о выборе.

**Comment by antonsoroko** [comment]
@elgatito проверил ещё раз - оно работает с фильмами, но не с эпизодами.
торренты находит правильные, вот дебаг лог с дебагом и от burst: https://paste.ubuntu.com/p/zWbd4NSnSk/

**Comment by elgatito** [comment]
Should be fixed by https://github.com/elgatito/elementum/commit/76af6d1049283e51ef6061112a65975dd3879628

**Comment by antonsoroko** [comment]
@elgatito работает, спасибо!
